---
- name: Disable Selinux and Firewall
  hosts: kubemaster kubeworkers
  user: ansible
  become: true

  tasks:
  - name: Disable Selinux
    shell:
      cmd: setenforce 0

  - name: Disable Permanently
    shell: 
      cmd: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

#  - name: Disable firewalld 
#      service: 
#        name: firewalld
#        state: disabled

