---
- name: EXCHANGING chrony.conf file WITH ALL BOXES!!
  hosts: timeservers
  user: ansible
  become: true
  vars:
   pkg: /ansible/PROJECT-6/playbooks/chrony_serv/chrony.conf

  tasks:
  - name: installing chrony
    yum:
      name: chrony
      state: present 
#  tasks:
#  - name: Copying
#    copy:
#      src: "{{ pkg }}" 
#      dest: /etc/chrony.conf
      notify: restart chronyd
  handlers:
  - name: restart chronyd
    service:
      name: chronyd
      state: restarted
      enabled: yes
