---
- name: EXCHANGING chrony.conf file WITH ALL BOXES!!
  hosts: centos6
  user: ansible
  become: true
  vars:
    pkg: /ansible/playbooks/chrony.conf

  tasks:
  - name: installing chrony
    yum:
      name: chrony
      state: present 
 
  tasks:
  - name: Copying
    copy:
      src: "{{ pkg }}"
      dest: /etc/chrony.conf
      notify: restart chronyd

  handlers:
  - name: restart chronyd
    service:
      name: chronyd
      state: restarted
      enabled: yes
